UPCOMING_CONTEST_STICKERS = [
    "CAACAgUAAxkBAAEJmghixAR5YQ7TYHsP9YW9eIJujbj2rAACbgUAAtzlyVcClcSeNfTeFikE",
    "CAACAgUAAxkBAAEJmgpixAS0j1LAcUvBcAABiz9CyDGLfOYAArQAA1joRwV4QOlBtbm68CkE"
]

OK_STICKERS = [
    "CAACAgUAAxkBAAEJmg1ixAUHFYRgn-CuEpo9lh0AAQ3RwNwAAloEAAIPpFBUzFUHPT66lMIpBA",
    "CAACAgUAAxkBAAEJmg5ixAUHWUlJfcP1D54_LYV0dmvTuQACRQQAAn46UFR8AAEGrSnsQMopBA",
    "CAACAgUAAxkBAAEJmg9ixAUHO4UWlLGTN-Y6ib19tkY8VwAC3gQAAgN-SFS4oEbO9p4-kykE",
    "CAACAgUAAxkBAAEJmhBixAUHrFAg0Rs_XWG1DN6sX3mx1AACHgQAAu4M4VcAAUOnOfYm8t0pBA",
    "CAACAgUAAxkBAAEJ1bVi4Cs9JKH1DGsQgHxH_h-zNVzHHQAC-AMAAj5lQVVAOHH72giz7ykE",
    "CAACAgUAAxkBAAEJ1bpi4CukGZmYUAVD-tfgAAGfX2VkFKUAAtAFAAJahklUtw40HpHEdVIpBA",
    "CAACAgUAAxkBAAEJ1cBi4CzAPRO6xB_sdkz-IOWMvTGyVgACCgADLQWvJP9Elb4G3p-PKQQ",
    "CAACAgUAAxkBAAEJ1cli4C_IZe0dL7ZVhhOrZWD3cayXmgACNAADLQWvJEyIUQV3fU0EKQQ"
]

FAILED_STICKERS = [
    "CAACAgIAAxkBAAEJmhVixAXDRugwZRz4Hwre90JP8h429QACcxIAAujW4hKWUrYzeg4kNSkE",
    "CAACAgUAAxkBAAEJmhZixAXDjrzRA7HW1jhNFVMbP0nC0wACSgQAAkFokFRpXByokaFRESkE",
    "CAACAgUAAxkBAAEJmhdixAXDH8p3ZxwZ0Ot7BafddRcutAAC3gMAAn3ROFc1RWpaahsG5CkE",
    "CAACAgUAAxkBAAEJ1bdi4CtRBrGU64nTdWyUMp8PCUs2GQACsAIAAlH0uVSFL2tgUGd-QCkE"
]
