UPCOMING_CONTEST_STICKERS = [
    "CAACAgUAAxkBAAEJmghixAR5YQ7TYHsP9YW9eIJujbj2rAACbgUAAtzlyVcClcSeNfTeFikE",
    "CAACAgUAAxkBAAEJmgpixAS0j1LAcUvBcAABiz9CyDGLfOYAArQAA1joRwV4QOlBtbm68CkE"
]

OK_STICKERS = [
    "CAACAgUAAxkBAAEJmg1ixAUHFYRgn-CuEpo9lh0AAQ3RwNwAAloEAAIPpFBUzFUHPT66lMIpBA",
    "CAACAgUAAxkBAAEJmg5ixAUHWUlJfcP1D54_LYV0dmvTuQACRQQAAn46UFR8AAEGrSnsQMopBA",
    "CAACAgUAAxkBAAEJmg9ixAUHO4UWlLGTN-Y6ib19tkY8VwAC3gQAAgN-SFS4oEbO9p4-kykE",
    "CAACAgUAAxkBAAEJmhBixAUHrFAg0Rs_XWG1DN6sX3mx1AACHgQAAu4M4VcAAUOnOfYm8t0pBA"
]

FAILED_STICKERS = [
    "CAACAgIAAxkBAAEJmhVixAXDRugwZRz4Hwre90JP8h429QACcxIAAujW4hKWUrYzeg4kNSkE",
    "CAACAgUAAxkBAAEJmhZixAXDjrzRA7HW1jhNFVMbP0nC0wACSgQAAkFokFRpXByokaFRESkE",
    "CAACAgUAAxkBAAEJmhdixAXDH8p3ZxwZ0Ot7BafddRcutAAC3gMAAn3ROFc1RWpaahsG5CkE"
]
